name: Feature request
description: Suggest an idea for this project
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug in the project.
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. **Example:** "I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen. **Example:** "I would like to have [...]"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered. **Example:** "I have considered [...]"
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Developer Help
      description: |
        Add any other context that may help the developer getting started with the issue

        Tip: You can attach images or give some steps to solve the issue
    validations:
      required: false